import Link from "next/link";
import { ArrowRight, BarChart3, Bot, Building2, CheckCircle2, CirclePause, Clock3, Database, FileCheck2, FileSearch, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { SearchBar } from "@/components/ui/SearchBar";
import { MetricCard } from "@/components/ui/MetricCard";
import { ProjectCard } from "@/components/obras/ProjectCard";
import { obras } from "@/data/obras";

export default function Home() {
  return (
    <>
      <section className="relative overflow-hidden border-b border-slate-200 bg-white">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_20%,#dbeafe_0,transparent_28%)]" />
        <div className="container-shell relative grid items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
          <div><span className="eyebrow"><Sparkles size={14} /> Transparencia pública con evidencia</span><h1 className="mt-6 max-w-3xl text-4xl font-bold leading-tight tracking-tight text-[#123B63] sm:text-5xl lg:text-6xl">Entiende qué pasa con las <span className="text-blue-600">obras públicas</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Busca una obra, revisa su avance y conoce las causas registradas de sus retrasos con explicaciones claras y evidencias verificables.</p><div className="mt-8"><SearchBar /></div><div className="mt-4 flex flex-wrap items-center gap-4"><Link href="/obras" className="btn-secondary">Explorar obras <ArrowRight size={16} /></Link><span className="flex items-center gap-1.5 text-xs font-semibold text-slate-500"><Bot size={15} className="text-blue-600" /> Análisis asistido por Gemma 4</span></div></div>
          <div className="relative mx-auto w-full max-w-xl">
            <div className="card relative overflow-hidden p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Seguimiento de avance</p><h2 className="mt-1 font-bold text-[#123B63]">I.E. San Martín</h2></div><span className="badge bg-amber-50 text-amber-800">Retrasada</span></div><div className="mt-8 grid grid-cols-2 gap-4"><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-700">Programado</p><p className="mt-1 text-3xl font-bold text-[#123B63]">70%</p></div><div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs text-emerald-700">Ejecutado</p><p className="mt-1 text-3xl font-bold text-[#0F9D78]">48%</p></div></div><div className="mt-7 flex h-32 items-end gap-3" aria-hidden="true">{[28,38,49,58,66,70].map((value, i) => <div key={value} className="flex h-full flex-1 items-end gap-1"><div className="w-1/2 rounded-t bg-blue-200" style={{height:`${value}%`}}/><div className="w-1/2 rounded-t bg-emerald-500" style={{height:`${[20,28,34,39,44,48][i]}%`}}/></div>)}</div><div className="mt-5 flex items-start gap-3 rounded-xl border border-slate-200 p-4"><FileCheck2 className="mt-0.5 shrink-0 text-blue-600" size={20}/><div><p className="text-sm font-bold text-[#123B63]">Conclusión con respaldo</p><p className="mt-1 text-xs leading-5 text-slate-500">Cada explicación indica el documento y fragmento utilizado.</p></div></div></div>
          </div>
        </div>
      </section>

      <section className="container-shell py-14"><div className="mb-7"><span className="eyebrow">Panorama de demostración</span><h2 className="section-title mt-3">Indicadores generales</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Obras monitoreadas" value="6" note="En 6 regiones" icon={Building2}/><MetricCard label="En ejecución" value="2" note="Seguimiento activo" icon={TrendingUp} tone="green"/><MetricCard label="Con retraso" value="2" note="Requieren atención" icon={Clock3} tone="amber"/><MetricCard label="Paralizadas" value="1" note="Alerta crítica" icon={CirclePause} tone="red"/></div></section>

      <section className="border-y border-slate-200 bg-white py-16"><div className="container-shell"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span className="eyebrow">Seguimiento ciudadano</span><h2 className="section-title mt-3">Obras destacadas</h2><p className="mt-2 text-slate-600">Datos simulados para demostrar el funcionamiento del portal.</p></div><Link href="/obras" className="btn-secondary self-start">Ver todas <ArrowRight size={16}/></Link></div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{obras.slice(0,3).map((obra)=><ProjectCard key={obra.id} obra={obra}/>)}</div></div></section>

      <section id="como-funciona" className="container-shell scroll-mt-24 py-16"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">Cómo funciona</span><h2 className="section-title mt-3">De documentos técnicos a información útil</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[{icon:Database,title:"Buscamos información pública",text:"Organizamos documentos y registros asociados a cada obra."},{icon:Bot,title:"Gemma analiza los documentos",text:"Identifica estados, causas, acciones pendientes y fragmentos relevantes."},{icon:FileSearch,title:"Mostramos explicación y evidencia",text:"Traducimos lo técnico a lenguaje claro sin ocultar la fuente original."}].map((step,i)=><article className="card p-6" key={step.title}><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-xl bg-blue-50 text-blue-700"><step.icon/></span><span className="text-4xl font-bold text-slate-100">0{i+1}</span></div><h3 className="mt-5 text-lg font-bold text-[#123B63]">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{step.text}</p></article>)}</div><div className="mt-6 flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-5"><ShieldCheck className="shrink-0 text-blue-700"/><p className="text-sm leading-6 text-blue-950"><strong>Gemma no reemplaza la fuente original.</strong> Cada conclusión debe conservar una ruta clara hacia el documento y el fragmento que la sustenta.</p></div></section>

      <section className="bg-[#123B63] py-14 text-white"><div className="container-shell flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div className="max-w-3xl"><span className="flex items-center gap-2 text-sm font-bold text-blue-200"><CheckCircle2 size={18}/> Compromiso de transparencia</span><h2 className="mt-4 text-2xl font-bold sm:text-3xl">Información clara, sin conclusiones ocultas</h2><p className="mt-3 leading-7 text-blue-100">ObraClara no determina culpables ni inventa información. Resume los datos encontrados en los documentos y muestra la evidencia utilizada.</p></div><Link href="/analizar" className="btn-white shrink-0">Probar análisis <BarChart3 size={17}/></Link></div></section>
    </>
  );
}
